clock/urls.py
from django.urls import path

from . import views

urlpatterns = [    
    path('', views.time),
    path('<int:hour>/', views.time)
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
]

jadwal/urls.py
from django.urls import path

from . import views

app_name = "jadwal"

urlpatterns = [    
    path ('', views.index, name="index"),
    path ('form/', views.jadwal, name='form'),
    path ('detail/', views.semua, name="semua"),
    path ('detail/<int:index>/', views.detail, name="detail"),
]

story/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')), 
    path('time/', include('clock.urls')),
    path('jadwal/',include('jadwal.urls')),
    path('kegiatan/', include('story6.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story6/urls.py
from django.urls import path

from . import views

app_name = "story6"

urlpatterns = [    
    path ('', views.index_kegiatan, name="index"),
    path ('form/', views.kegiatan, name='form'),
    path ('detail/', views.list_kegiatan, name="semua"),
    path ('detail/<int:id>/', views.detail_kegiatan, name="detail"),
    path ('detail/delete/<int:id>/', views.delete_peserta, name="delete")
]

clock/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models


# Create your models here.
class Jadwal(models.Model):
    pilihan_semester= (
        ('Genap', "Genap"),
        ('Gasal', 'Gasal')
    )
    nama = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    sks = models.PositiveSmallIntegerField(default=1)
    semester = models.CharField(max_length=100, choices=pilihan_semester, default="Gasal")
    tahun = models.CharField(max_length=100)
    ruang = models.CharField(max_length=100)
    deskripsi = models.TextField(max_length=100)

    def __str__(self):
        return f'{self.nama}'

class Tugas(models.Model):
    nama_tugas = models.CharField(max_length=100)
    deadline_tugas =models.DateField()
    nama_matkul =models.ForeignKey(Jadwal, on_delete = models.CASCADE)

story1/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=100)
    deskripsi_kegiatan = models.TextField()

    def __str__(self):
        return self.nama_kegiatan

class Peserta(models.Model):
    nama_peserta = models.CharField(max_length=100)
    ikut_kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.nama_peserta

jadwal/forms.py
from django import forms
from .models import Jadwal

class madwal(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = "__all__"
        labels = {
            'nama'      : "Nama Jadwal",
            'dosen'      : "Nama Dosen",
            'sks'       : "Jumlah SKS",
            'semester'  : "Semester",
            'tahun'     : "Tahun Ajar",
            'ruang'     : 'Ruang',
            'deskripsi' : 'Deskripsi Mata Kuliah',
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        }
        )

story6/forms.py
from django import forms
from .models import Kegiatan, Peserta

class IkutKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = "__all__"
        labels = {
            'nama_kegiatan'     : "Nama Kegiatan",
            'deskripsi_kegiatan': "Deskripsi",
            
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        }
        )

class JoinKegiatan(forms.ModelForm):
    class Meta:
        model = Peserta
        fields =["nama_peserta"]
        labels ={
            'nama_peserta' : "Nama Peserta",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        }
        )

clock/views.py
from django.shortcuts import render
from datetime import timedelta
import datetime
 

def time(request, hour=0):
    currentDT = datetime.datetime.now() + timedelta(hours=hour) 
    hour = currentDT.hour
    minute = currentDT.minute
    second = currentDT.second
    return render(request, "time.html", {"hour": hour, 'minute': minute, 'second':second})

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def profile(request):
    return render(request, 'profile.html')

jadwal/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import madwal
from .models import Jadwal, Tugas

# Create your views here.
def index (request):
    return render(request,"mindex.html")

def jadwal(request):
    if request.method == 'POST':
        form = madwal(request.POST)
        if form.is_valid():
            form.save()
            return redirect('jadwal:form')
    else:
        messages.warning(request,"Jadwal gagal ditambahkan")
        form = madwal()
        return render(request, "form.html", {"form" : form,})

def semua(request):
    semua = Jadwal.objects.all()
    if request.method == "POST":
        data = Jadwal.objects.get(pk=request.POST["idhapus"])
        data.delete()
    return render(request, "semua.html", {"semua":semua})


def detail(request, index):
    detail = Jadwal.objects.get(pk=index)
    matkul = Tugas.objects.filter(nama_matkul=detail)
    return render(request,'detail.html', {"detail":detail, "matkul":matkul})

story1/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request,"home.html")

story6/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import IkutKegiatan, JoinKegiatan
from .models import Kegiatan, Peserta
# Create your views here.
def index_kegiatan (request):
    return render(request,"index_kegiatan.html")

def kegiatan(request):
    if request.method == 'POST':
        form = IkutKegiatan(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('story6:form')
    else:
        form = IkutKegiatan()
        return render(request, "form_kegiatan.html", {"form" : form})

def list_kegiatan(request):
    semua_kegiatan = Kegiatan.objects.all()
    semua_peserta = Peserta.objects.all()
    if request.method == "POST":
        return render(request, "form_peserta.html")
    return render(request, "list_kegiatan.html", {"semua":semua_kegiatan, "peserta":semua_peserta})


def detail_kegiatan(request, id=0):
    if request.method == "POST": 
        peserta = JoinKegiatan(request.POST or None)
        if peserta.is_valid():
            penumpang = Peserta(ikut_kegiatan=Kegiatan.objects.get(pk = id), nama_peserta=peserta.data['nama_peserta'])
            penumpang.save() 
        return redirect('/kegiatan/detail')
    peserta = JoinKegiatan()
    return render(request, "form_peserta.html",{'peserta':peserta})

def delete_peserta(request, id):
    peeps = Peserta.objects.get(pk= id)
    peeps.delete()
    return redirect('/kegiatan/detail')

    

clock/templates/time.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jam Beker</title>
</head>
<body>
    <h1>Sekarang Jam :</h1>
    <h1>{{ hour }} : {{ minute }} : {{ second }}</h1>
</body>
</html>

homepage/templates/includes/base.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Salman Marsha</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

homepage/templates/includes/navbar.html
{% block content %}
{% load static %}
    <nav class="col-md-12 navbar navbar-expand-lg navbar-light bg-light navbar-css fixed-top">
      <a class="navbar-brand nav-photo" href="#"><img src="{% static 'juleha.png' %}" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"></button>
       <div class="collapse navbar-collapse navbar-link" id="navbarNav">
         <ul class="navbar-nav">
           <li class="nav-item">
             <a class="nav-link" href="{% url 'homepage:index' %}" >Halaman Utama</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'homepage:profile' %}">Profil</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'story1:index' %}">Story 1</a>
           </li>
           <li class="nav-item">
            <a class="nav-link" href="{% url 'jadwal:index' %}">AturJadwal</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'story6:index' %}">AturKegiatan</a>
          </li>
         </ul>
       </div>
    </nav> 
{% endblock content %}

homepage/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'includes/base.html' %}
<body>  
  {% include 'includes/navbar.html' %}
  <div class="side-barr">
    <table>
      <tr>
        <td><a href="https://web.facebook.com/salman.marsha">
          <img src="{% static 'facebook white.svg' %}"></a></td> 
      </tr>
      <tr>
        <td><a href="https://www.instagram.com/salmanmarsha_/"><img src="{% static 'Instagram white.svg' %}"></a></td>
      </tr>
      <tr>
        <td><a href="https://www.linkedin.com/in/salman-marsha-5061b214b"><img src="{% static 'Linkedin white.svg' %}"></a></td>
      </tr>
      <tr>
        <td><a href="https://twitter.com/SalmanMarsha1"></a><img src="{% static 'twitter black.svg' %}"></a></td>
      </tr>
    </table>
</div>


 <div class="container" id="main-page">
  <div class="container d-flex flex-column flex-md-row">
    <div class="photo">
      <img src="{% static 'round.png' %}">
  </div>
  <div class="body-main">
      <p>Hai,</p>
      <p>aku Salman Marsha</p>
  </div>
  </div>
  </div>
  
  <div class="container" id="second-page">
    <div class="row">
      <div class="d-flex flex-column">
        <div class="title-white">
          <p>Tentang Saya</p>
        </div>
        <p class="">Saya adalah mahasiswa Fasilkom UI yang sedang menggeluti mata kuliah 
        Perancangan dan Pemrograman Web untuk mencapai impian saya, yaitu menjadi 
        Web Developer.</p>
      </div>
    </div>
  </div>

  <div class="container" id="third-page">
    <div class="row">
    <div class="d-flex flex-column">
      <p class="title-black">Keahlian</p>
      <p class="">Saya cukup ahli dalam menggunakan Python, Flask, HTML, dan sekarang sedang
      mengembangkan Java, CSS, Git, dan Javascript.</p>
      <div class="git-photo">
        <a href="https://gitlab.com/SalmanMarsha">
          <img class="git-photo" src="{% static 'gitlab.svg' %}"></a>
      </div>
      </div>
  </div>
</div>

  <div class="container" id="fourth-page">
    <div class="row caro">
      <div class=" col-md-12 d-flex flex-column">
      <p class="small-idea">Ada ide?</p c>
      <p class="big-idea">Ayo Diskusikan!</p>
      <div class="caro d-flex justify-content-center">
        <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModal">
          Interest
        </button>
      </div>
      <div class="size-med">
        <ul>
          <li><img src="{% static 'phone.png' %}"> (+62)82251142255</li>
          <li><img src="{% static 'Mail.svg' %}"> salman.marsha@ui.ac.id</li>
        </ul>
      </div>
    </div>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">My Interest</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img class="d-block w-100" src="{% static "HTML5.svg" %}" alt="First slide">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" src="{% static "CSS3.svg" %}" alt="Second slide">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" src="{% static "JS.svg" %}" alt="Third slide">
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</html>

homepage/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'includes/base.html' %}
<body>
    {% include 'includes/navbar.html' %}
    <div class="back-sign">
        <a href="{% url 'homepage:index' %} "><img src="{% static 'back-sign.svg' %}"></a>
    </div>
    <div class="container">
        <div class="d-flex flex-row  main-page-profile">
            <div class="photo-profile center">
                <img src="{% static 'profile.jpg' %}">
            </div>
            <div class="name-profile">
                <h1 class="salman">Salman</h1>
                <h1 class="marsha">Marsha</h1>
            </div>
        </div>
    </div>

    <div class="container biodata-sec"> 
        <div class="row d-flex">
            <p class="title-profiles">Biodata</p>
            <div class="col-sm-12 table-profile">
                <table>
                    <tr>
                        <td>Nama</td>
                        <td>:</td>
                        <td>Salman Marsha</td>
                    </tr>
        
                    <tr>
                        <td>Nama Panggilan</td>
                        <td>:</td>
                        <td>Salman Marsha</td>
                    </tr>
        
                    <tr>
                        <td>Tempat, Tanggal Lahir</td>
                        <td>:</td>
                        <td>Palangka Raya, 2 Maret 2002</td>
                    </tr>
                    
                    <tr>
                        <td>Nomor HP</td>
                        <td>:</td>
                        <td>082251142255</td>
                    </tr>
        
                    <tr>
                        <td>Hobi</td>
                        <td>:</td>
                        <td>Melihat Pola</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="container riwayat-sec">
        <div class="row d-flex">
            <p class="title-profiles"> Riwayat Pendidikan</p>
            <div class="col-md-12 table-profile table-center">
                <table>
                    <tr>
                        <td>
                            <div class="">
                                <p><u>SD Negeri 10 Palangka Raya</u></p>
                                <br>
                                <p>2007-2013</p>
                            </div>
                        </td>
                        <td>
                            <div>
                                <p><u>SMP Negeri 2 Palangka Raya</u></p>
                                <br>
                                <p>2007-2013</p>
                            </div>
                        </td>
                        <td>
                            <div>
                                <p><u>SMA Negeri 2 Palangka Raya</u></p>
                                <br>
                                <p>2007-2013</p>
                            </div>
                        </td>
                        <td>
                            <div>
                                <p><u>Kuliah</u></p>
                                <br>
                                <p>2019-Sekarang</p>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="organisasi-sec">
            <p class="title-profiles">Organisasi</p>
            <div class="table-profile table-center">
                <p>Reporter Jurnalistik Smada</p>
                <p>2016-2017</p>

                <br>

                <p>Ketua Divisi Reporter Jurnalistik Smada</p>
                <p>2017-2018</p>

                <br>

                <p>Wakil Ketua Bidang Humas</p>
                <p>2019-Sekarang</p>
            </div>
        </div>
    </div>

    <div class="container">
    
        <p class="title-profiles">Kontak:</p>
        <div class="footer-profile">
        <ul>
            <li><a href="https://web.facebook.com/salman.marsha">
              <img src="{% static 'facebook white.svg' %}" width="50" height="50"></a></li>
            <li><a href='https://www.instagram.com/salmanmarsha_/'><img src="{% static 'Instagram white.svg' %}"></a></li>
            <li><a href='https://www.linkedin.com/in/salman-marsha-5061b214b'><img src="{% static 'Linkedin white.svg' %}"></a></li>
            <li><a href='https://twitter.com/SalmanMarsha1'></a><img src="{% static 'twitter black.svg' %}"></a></li>
          </ul>

        </div>
</div>

</body>
</html>

jadwal/templates/detail.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AturJadwal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href= "{% static 'style1.css' %}">
</head>
<body>
    <div class="container details">
        <div class="row">
            <h1>{{ detail.nama }}</h1>
        </div>
        <div class="kotak-detail">
            <div class="row">
                <div class="col-4"><h3>Dosen Pengajar</h3></div>
                <div class="col-auto">:</div>
                <div class="col-7">{{ detail.dosen }}</div>
            </div>
            <div class="row">
                <div class="col-4"><h3>Bobot SKS</h3></div>
                <div class="col-auto">:</div>
                <div class="col-7">{{ detail.sks }} SKS</div>
            </div>
            <div class="row">
                <div class="col-4"><h3>Tahun Ajaran</h3></div>
                <div class="col-auto">:</div>
                <div class="col-7">{{ detail.semester }} {{ detail.tahun }}</div>
            </div>
            <div class="row">
                <div class="col-4"><h3>Ruang</h3></div>
                <div class="col-auto">:</div>
                <div class="col-7">Ruang {{ detail.ruang }}</div>
            </div>
            <br>
            <br>
            <div class="deskripsi">
                <h3>Deskripsi:</h3>
                {{ detail.deskripsi }}
            </div>


            <div class="tugas">
                <br>
                <br>
                <h2>Tugas: </h2>
                    {% for elemen in matkul %}
                <div class="">
                    {{ elemen.nama_tugas }}
                    {{ elemen.deadline_tugas }}

                    {% endfor %}
                </div>
            </div>
        </div>
        <!--<div class="igomid">
             <table>
                <tr>
                    <td>Dosen Pengajar</td>
                    <td>:</td>
                    <td>{{ detail.dosen }}</td>
                </tr>
                <tr>
                    <td>SKS</td>
                    <td>:</td>
                    <td>{{ detail.sks }}</td>
                </tr>
                <tr>
                    <td>Semester</td>
                    <td>:</td>
                    <td>{{ detail.semester }}</td>
                </tr>
                <tr>
                    <td>Tahun Ajaran</td>
                    <td>:</td>
                    <td>{{ detail.tahun }}</td>
                </tr>
                <tr>
                    <td>Ruang</td>
                    <td>:</td>
                    <td>{{ detail.ruang }}</td>
                </tr>
            </table>
        </div>
        <div>
            <p>Deskripsi</p>
            <p>{{ detail.deskripsi }}</p>
        </div> -->
    </div>
    <div>

    </div>
</body>
</html>

jadwal/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'includes/base.html' %}
<body>
    <div class="container">
        <div class="row">
            <div class="main-title col-sm-3">
                <p>Buat Jadwal</p>
            </div>
            <div class="col-sm-6"></div>
            <div class="main-title col-sm-3">
                <a href= "{% url 'jadwal:semua' %}">List Jadwal</a>
            </div>
        </div>
        <div class="centering font-title mt-5">
            <h1>Ayo Susun Jadwalmu!</h1>
        </div>

        <div class="formku ">
            <form action="" method="POST">
                {% csrf_token %}    
                {{ form }}
                <div class="buttonk">
                    <button type="submit" class="btn btn-dark">Submit</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

jadwal/templates/mindex.html
{% load static %}
<!DOCTYPE html>
{% include 'includes/base.html' %}
{% include 'includes/navbar.html' %}
<body>
    <div class="container">
        <div class="main-jadwal">
            <hr class="hr-css">
            <h1>Selamat Datang di AturJadwal</h1>
            <h4>Sebuah <i>web-based schedule organizer</i> buatan Salman Marsha</h4>
            <hr class="hr-css">
        </div>
        <div class="d-flex justify-content-center">
            <table>
                <tr>
                    <td>
                        <a class="btn btn-dark" href= "{% url 'jadwal:form' %}">Buat Jadwal</a>
                    </td>
                    <td>
                        <a class="btn btn-dark" href= "{% url 'jadwal:semua' %}">List Jadwal</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</body>
</html>

story6/templates/form_kegiatan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'includes/base.html' %}
<section>
    <!-- Header -->
    <div class="container">
        <div class="row">
            <div class="main-title col-sm-3">
                <p>Buat Kegiatan</p>
            </div>
            <div class="col-sm-6"></div>
            <div class="main-title col-sm-3">
                <a href= "{% url 'story6:semua' %}">List Kegiatan</a>
            </div>
        </div>
        <div class="centering font-title mt-5">
            <h1>Ayo Buat Kegiatan!</h1>
        </div>  
        <!-- Form -->
        <div class="formku ">
            <form action="" method="POST">
                {% csrf_token %}    
                {{ form }}
                <div class="buttonk">
                    <button type="submit" class="btn btn-dark">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
</html>

story6/templates/form_peserta.html
<!DOCTYPE html>
<html lang="en">
    {% include 'includes/base.html' %}
<section>
    <div class="">
        <button type="submit" class="btn btn-dark">Back</button>
    </div>
    <div class="d-flex align-items justify-content-center">
        <form action="" method="POST">
            {% csrf_token %}    
            {{ peserta }}
            <input type="hidden" value="{{ event.id }}" name="tambah">
            <div class="buttonk">
                <button type="submit" class="btn btn-dark">Submit</button>
            </div>
        </form>
    </div>
</section>
</html>

story6/templates/index_kegiatan.html
{% load static %}
<!DOCTYPE html>
{% include 'includes/base.html' %}
{% include 'includes/navbar.html' %}
<section>
    <!-- Index -->
    <div class="container">
        <div class="main-jadwal">
            <hr class="hr-css">
            <h1>Selamat Datang di AturKegiatan</h1>
            <h4>Sebuah <i>web-based activity organizer</i> buatan Salman Marsha</h4>
            <hr class="hr-css">
        </div>
        <div class="d-flex justify-content-center">
            <table>
                <tr>
                    <td>
                        <a class="btn btn-dark" href= "{% url 'story6:form' %}">Buat Kegiatan</a>
                    </td>
                    <td>
                        <a class="btn btn-dark" href= "{% url 'story6:semua' %}">List Kegiatan</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</section>
</html>

story6/templates/list_kegiatan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'includes/base.html' %}
<section>
    <!-- Header -->
    <div class="container">
        <div class="row">
            <div class="main-title col-sm-3">
                <a href= "{% url 'story6:form' %}">Buat Kegiatan</a>
            </div>
            <div class="col-sm-6"></div>
            <div class="main-title col-sm-3">
                <p>List Kegiatan</p>
            </div>
        </div>
    </div>
    <div class="centering font-title mt-5">
        <h1>List Jadwal</h1>
    </div>
    <!-- content -->
    {% for elemen in semua %}
    <div class="container">
        <div class="nama-title">
            <div class="centering">
                <h1><u>{{ elemen.nama_kegiatan }}</u></h1>
                <p id="ahmad">{{ elemen.deskripsi_kegiatan }} </p>
            </div>
            <div>
                <h3>Peserta:</h3>
                {% for target in peserta %}
                {% if target.ikut_kegiatan == elemen %}
                <div class="d-flex justify-content-between mt-5 ml-5">
                    <h4>{{ target.nama_peserta }}</h4>
                    <button type="submit" class="btn btn-dark"><a href=" {% url 'story6:delete' id=target.id %}">Hapus Peserta</a></button>
                    
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="buttonk">
                    <button type="submit" class="btn btn-dark"><a href=" {% url 'story6:detail' id=elemen.id %}">Tambah Peserta</a></button>
                </div>
            </form>
        </div>
    </div>
    {% endfor %}
</section>
</html>